import { Rarity, ICard } from './types';

// New Color Palette based on User Feedback ("agradable a la vista")
// Using softer backgrounds but stronger borders/accents for distinctiveness.
export const RARITY_COLORS = {
  [Rarity.COMMON]: 'border-gray-300 bg-white text-gray-800 shadow-sm',
  [Rarity.RARE]: 'border-blue-300 bg-gradient-to-br from-blue-50 to-white text-blue-900 shadow-blue-100',
  [Rarity.EPIC]: 'border-purple-300 bg-gradient-to-br from-purple-50 to-white text-purple-900 shadow-purple-100',
  [Rarity.LEGENDARY]: 'border-amber-300 bg-gradient-to-br from-amber-50 to-white text-amber-900 shadow-amber-100',
  [Rarity.SPECIAL]: 'border-emerald-300 bg-gradient-to-br from-emerald-50 to-white text-emerald-900 shadow-emerald-100',
};

export const RARITY_BADGE_COLORS = {
  [Rarity.COMMON]: 'bg-gray-200 text-gray-600',
  [Rarity.RARE]: 'bg-blue-100 text-blue-600',
  [Rarity.EPIC]: 'bg-purple-100 text-purple-600',
  [Rarity.LEGENDARY]: 'bg-amber-100 text-amber-600',
  [Rarity.SPECIAL]: 'bg-emerald-100 text-emerald-600',
};

// Helper to generate IDs
const uuid = () => Math.random().toString(36).substr(2, 9);

export const INITIAL_DECK: ICard[] = [
  // --- COMMON (WHITE/GRAY) ---
  { id: uuid(), rarity: Rarity.COMMON, title: "Modo Avión Activado", description: "Debes guardar tu celular por 1 hora para platicar o estar presente sin distracciones." },
  { id: uuid(), rarity: Rarity.COMMON, title: "Tú eliges la cena", description: "Se termina el dilema de '¿qué quieres comer?'; tú decides y el otro acepta." },
  { id: uuid(), rarity: Rarity.COMMON, title: "El DJ del momento", description: "Si están juntos o en llamada, tú controlas la música o el audio por 30 minutos." },
  { id: uuid(), rarity: Rarity.COMMON, title: "Antojo compartido", description: "El receptor debe enviar el nombre de un dulce o botana que ambos amen para el próximo encuentro." },
  { id: uuid(), rarity: Rarity.COMMON, title: "Voto de Confianza", description: "El receptor debe permitir que el lanzador tome una decisión trivial por él hoy (ej. qué ponerse)." },
  { id: uuid(), rarity: Rarity.COMMON, title: "Sin Filtros", description: "El receptor debe enviar una selfie graciosa 'al natural' o sin filtros en este instante." },
  { id: uuid(), rarity: Rarity.COMMON, title: "Foto de 'ahorita'", description: "Si están lejos, el receptor debe enviar una foto de lo que ve en su entorno justo ahora." },
  { id: uuid(), rarity: Rarity.COMMON, title: "Elegir el Outfit", description: "Tú decides qué ropa usará tu pareja para la siguiente vez que salgan juntos." },
  { id: uuid(), rarity: Rarity.COMMON, title: "Despertador Cariñoso", description: "Mañana el receptor debe llamar o escribir un mensaje de voz tierno a la hora acordada." },
  { id: uuid(), rarity: Rarity.COMMON, title: "Encargado de la Luz", description: "Si están juntos, el receptor debe levantarse a apagar luces o cerrar puertas hoy." },
  { id: uuid(), rarity: Rarity.COMMON, title: "Resumen sin interrupciones", description: "El receptor debe escuchar tu historia por 10 minutos sin decir una sola palabra." },
  { id: uuid(), rarity: Rarity.COMMON, title: "Mandar el Meme", description: "El receptor tiene que buscar y enviarte 3 memes que sepa que te harán reír." },
  { id: uuid(), rarity: Rarity.COMMON, title: "Organizador de Agenda", description: "El receptor debe proponer 3 planes diferentes para la próxima salida." },
  { id: uuid(), rarity: Rarity.COMMON, title: "La Próxima Serie", description: "Tú eliges la siguiente serie o película que empezarán a ver juntos." },
  { id: uuid(), rarity: Rarity.COMMON, title: "Cumplido por Mensaje", description: "El receptor debe enviar un mensaje de texto con un piropo creativo ahora mismo." },
  { id: uuid(), rarity: Rarity.COMMON, title: "Cero Pantallas en la mesa", description: "Si están comiendo, los teléfonos quedan prohibidos hasta terminar." },
  { id: uuid(), rarity: Rarity.COMMON, title: "Notificación Prioritaria", description: "El receptor debe activar sonidos de notificación solo para tus mensajes por el resto del día." },
  { id: uuid(), rarity: Rarity.COMMON, title: "Limpieza Express", description: "Si están juntos, el receptor debe recoger o limpiar el espacio compartido hoy." },
  { id: uuid(), rarity: Rarity.COMMON, title: "Opinión Honesta", description: "El receptor debe responder con total sinceridad una pregunta trivial que le hagas." },
  { id: uuid(), rarity: Rarity.COMMON, title: "Trastes de Cortesía", description: "Si cocinaste para ambos, el receptor lava todo sin importar de quién era el turno." },
  { id: uuid(), rarity: Rarity.COMMON, title: "Bolsas del Súper", description: "El receptor debe cargar todas las bolsas pesadas en la próxima compra compartida." },
  { id: uuid(), rarity: Rarity.COMMON, title: "Llamada de Buenas Noches", description: "El receptor debe llamarte antes de dormir, sin excusas." },
  { id: uuid(), rarity: Rarity.COMMON, title: "El Vigilante", description: "Si quieres dormir una siesta, el receptor debe asegurar silencio total por 40 minutos." },
  { id: uuid(), rarity: Rarity.COMMON, title: "Decisión de Película", description: "Tú eliges qué ver hoy y el otro prepara las palomitas o botanas." },
  { id: uuid(), rarity: Rarity.COMMON, title: "Llamada de 5 Minutos", description: "El receptor debe llamarte solo para decirte algo lindo y colgar de inmediato." },
  { id: uuid(), rarity: Rarity.COMMON, title: "Sin Críticas al Menú", description: "El receptor debe comer lo que elijas sin hacer gestos ni comentarios negativos." },
  { id: uuid(), rarity: Rarity.COMMON, title: "Elige el Camino", description: "Tú decides la ruta o el medio de transporte para llegar a su siguiente destino juntos." },
  { id: uuid(), rarity: Rarity.COMMON, title: "Asistente de Compras", description: "El receptor te acompaña a una tienda por 20 minutos sin ver el reloj." },
  { id: uuid(), rarity: Rarity.COMMON, title: "Cambio de Sábanas", description: "Si están juntos, el receptor debe encargarse de tender y arreglar la cama hoy." },
  { id: uuid(), rarity: Rarity.COMMON, title: "Poner la Mesa", description: "El receptor debe preparar el área de comida con todo lo necesario antes de sentarse." },
  { id: uuid(), rarity: Rarity.COMMON, title: "Quitar la Mesa", description: "Tú te retiras y el receptor limpia y guarda todo lo que usaron para comer." },
  { id: uuid(), rarity: Rarity.COMMON, title: "Pausa de Estiramiento", description: "El receptor debe dejar lo que está haciendo y estirarse o caminar 2 minutos por salud." },
  { id: uuid(), rarity: Rarity.COMMON, title: "Sin Notificaciones", description: "El receptor debe silenciar todas sus redes sociales mientras estén juntos hoy." },
  { id: uuid(), rarity: Rarity.COMMON, title: "Pedido Especial", description: "El receptor debe agregar un antojo tuyo a la lista de compras del súper." },
  { id: uuid(), rarity: Rarity.COMMON, title: "Noche de Juegos", description: "El receptor debe jugar el videojuego o juego de mesa que elijas por 30 minutos." },
  { id: uuid(), rarity: Rarity.COMMON, title: "Lectura en voz alta", description: "El receptor debe leerte un artículo o noticia interesante mientras descansas." },
  { id: uuid(), rarity: Rarity.COMMON, title: "El Mejor Spot", description: "En un lugar público, tú eliges el asiento y el otro se acomoda después." },
  { id: uuid(), rarity: Rarity.COMMON, title: "Cero Sarcasmo", description: "El receptor tiene prohibido usar tonos irónicos por las próximas 3 horas." },
  { id: uuid(), rarity: Rarity.COMMON, title: "Mensaje de Buenos Días", description: "Mañana el receptor debe ser quien escriba primero con un mensaje especial." },
  { id: uuid(), rarity: Rarity.COMMON, title: "Cierre de App", description: "El receptor debe cerrar esa aplicación que lo distrae demasiado cuando están juntos hoy." },

  // --- RARE (BLUE) ---
  { id: uuid(), rarity: Rarity.RARE, title: "Emergencia de Cariño", description: "Se activa el protocolo; el receptor debe darte mimos y palabras bonitas por 15 min." },
  { id: uuid(), rarity: Rarity.RARE, title: "Masaje de 10 minutos", description: "El receptor debe darte un masaje relajante en la zona que tú elijas." },
  { id: uuid(), rarity: Rarity.RARE, title: "Carta de Amor Digital", description: "El receptor debe escribirte un párrafo detallado sobre algo que admire de ti." },
  { id: uuid(), rarity: Rarity.RARE, title: "Elogio por hora", description: "Durante las próximas 4 horas, el receptor debe decirte un cumplido cada vez que cambie la hora." },
  { id: uuid(), rarity: Rarity.RARE, title: "Cita en el Pasado", description: "El receptor debe contarte con detalle qué fue lo primero que pensó al conocerte." },
  { id: uuid(), rarity: Rarity.RARE, title: "Ambiente Relajante", description: "El receptor debe preparar una atmósfera de paz (velas o música) para ti hoy." },
  { id: uuid(), rarity: Rarity.RARE, title: "Playlist de 'Nosotros'", description: "El receptor debe enviarte una lista de 5 canciones que le recuerden a su relación." },
  { id: uuid(), rarity: Rarity.RARE, title: "Mimos en el Pelo", description: "El receptor debe acariciarte la cabeza por 15 minutos sin parar." },
  { id: uuid(), rarity: Rarity.RARE, title: "Mirada Fija", description: "Deben verse a los ojos por 1 minuto completo en silencio para reconectar." },
  { id: uuid(), rarity: Rarity.RARE, title: "Sesión de Fotos", description: "El receptor debe tomarte 5 fotos 'espontáneas' donde resalte tu belleza." },
  { id: uuid(), rarity: Rarity.RARE, title: "Cena Sorpresa", description: "El receptor tiene 48 horas para organizar una comida especial para ti." },
  { id: uuid(), rarity: Rarity.RARE, title: "Paseo de la Mano", description: "Si están fuera, deben caminar 10 minutos tomados de la mano." },
  { id: uuid(), rarity: Rarity.RARE, title: "Lista de Gratitud", description: "El receptor debe decirte 3 cosas que agradece de tenerte en su vida." },
  { id: uuid(), rarity: Rarity.RARE, title: "Abrazo de 1 Minuto", description: "Un abrazo largo y apretado sin decir una sola palabra." },
  { id: uuid(), rarity: Rarity.RARE, title: "Dormir de 'Cucharita'", description: "El receptor acepta ser la 'cuchara grande' (o pequeña) a tu petición." },
  { id: uuid(), rarity: Rarity.RARE, title: "Post-it Romántico", description: "El receptor debe esconder un mensaje lindo en algo que uses mañana." },
  { id: uuid(), rarity: Rarity.RARE, title: "Beso de Película", description: "El receptor debe darte un beso apasionado e inesperado ahora mismo." },
  { id: uuid(), rarity: Rarity.RARE, title: "Sueño Compartido", description: "El receptor debe contarte un viaje o plan que quiera hacer contigo a futuro." },
  { id: uuid(), rarity: Rarity.RARE, title: "Tarde de Picnic", description: "El receptor debe organizar una salida al aire libre para su próximo encuentro." },
  { id: uuid(), rarity: Rarity.RARE, title: "Cumplido Público", description: "El receptor debe decirte algo hermoso frente a alguien más hoy." },
  { id: uuid(), rarity: Rarity.RARE, title: "Video Dedicatoria", description: "El receptor debe grabarse diciendo por qué eres una persona especial." },
  { id: uuid(), rarity: Rarity.RARE, title: "Masaje de Manos", description: "El receptor debe hidratar y masajear tus manos por 5 minutos." },
  { id: uuid(), rarity: Rarity.RARE, title: "Recordatorio de Amor", description: "El receptor debe enviarte un 'Te amo' en un momento random del día." },
  { id: uuid(), rarity: Rarity.RARE, title: "Regalo Manual", description: "El receptor debe hacerte un detalle con papel o dibujo hoy mismo." },
  { id: uuid(), rarity: Rarity.RARE, title: "Abrazo Virtual", description: "Si están lejos, el receptor debe enviarte un audio describiendo cómo te abrazaría." },
  { id: uuid(), rarity: Rarity.RARE, title: "Cero Críticas", description: "Durante todo el día, el receptor solo puede decir cosas positivas de ti." },
  { id: uuid(), rarity: Rarity.RARE, title: "Baile en la Sala", description: "El receptor debe bailar una canción lenta contigo sin necesidad de una fiesta." },
  { id: uuid(), rarity: Rarity.RARE, title: "Pregunta Profunda", description: "Tú haces una pregunta sobre sentimientos y el otro debe ser 100% honesto." },
  { id: uuid(), rarity: Rarity.RARE, title: "Acompañante de Hobby", description: "El receptor debe ver un video o participar en algo que a ti te guste por 20 min." },
  { id: uuid(), rarity: Rarity.RARE, title: "Cena a la Luz de las Velas", description: "El receptor debe poner velas o luces tenues para su próxima comida juntos." },
  { id: uuid(), rarity: Rarity.RARE, title: "Susurro al Oído", description: "El receptor debe decirte algo pícaro o dulce muy bajito." },
  { id: uuid(), rarity: Rarity.RARE, title: "Cuidado de Piel", description: "El receptor debe ayudarte con una mascarilla o crema facial hoy." },
  { id: uuid(), rarity: Rarity.RARE, title: "Día Solo Nosotros", description: "El receptor cancela cualquier distracción menor para darte prioridad hoy." },
  { id: uuid(), rarity: Rarity.RARE, title: "Beso en la Frente", description: "El receptor debe saludarte o despedirse con este gesto hoy." },
  { id: uuid(), rarity: Rarity.RARE, title: "Promesa Pequeña", description: "El receptor debe comprometerse a una tarea simple y cumplirla hoy." },
  { id: uuid(), rarity: Rarity.RARE, title: "Elogio al Despertar", description: "Mañana lo primero que el receptor te diga debe ser un cumplido." },
  { id: uuid(), rarity: Rarity.RARE, title: "Audio de 1 Minuto", description: "Un mensaje de voz largo enumerando lo que más le gusta de ti." },
  { id: uuid(), rarity: Rarity.RARE, title: "Sin Celular en Cita", description: "Durante su próxima salida, el receptor no puede sacar el teléfono." },
  { id: uuid(), rarity: Rarity.RARE, title: "Mirar el Cielo", description: "Salgan a ver las estrellas o las nubes juntos por 5 minutos." },
  { id: uuid(), rarity: Rarity.RARE, title: "Vales de Cariño", description: "El receptor te entrega un vale escrito a mano por un 'favor especial'." },

  // --- EPIC (PURPLE) ---
  { id: uuid(), rarity: Rarity.EPIC, title: "Bandera Blanca", description: "Se detectó una emergencia de paz. El tema de discusión queda prohibido por hoy. No se menciona." },
  { id: uuid(), rarity: Rarity.EPIC, title: "Borrón y Cuenta Nueva", description: "Cualquier roce de hoy queda perdonado y olvidado instantáneamente." },
  { id: uuid(), rarity: Rarity.EPIC, title: "Disculpa Sincera", description: "El receptor debe reconocer un error reciente y pedir perdón sin justificarse." },
  { id: uuid(), rarity: Rarity.EPIC, title: "Veto de Mal Humor", description: "El receptor debe hacer un esfuerzo por cambiar su actitud negativa por 2 horas." },
  { id: uuid(), rarity: Rarity.EPIC, title: "Cero Orgullo", description: "El receptor acepta tu punto de vista en un tema en el que no estaban de acuerdo." },
  { id: uuid(), rarity: Rarity.EPIC, title: "Silencio de Calma", description: "Si lo pides, el receptor debe darte 20 minutos de paz sin hablarte." },
  { id: uuid(), rarity: Rarity.EPIC, title: "Escucha Activa", description: "El receptor debe repetir tus palabras para confirmar que te entendió bien." },
  { id: uuid(), rarity: Rarity.EPIC, title: "Abrazo de Reconciliación", description: "Un abrazo de 2 minutos para bajar la tensión si hay peleas." },
  { id: uuid(), rarity: Rarity.EPIC, title: "Cero Sarcasmo", description: "Prohibido usar ironía o burlas en momentos de diferencia de opinión hoy." },
  { id: uuid(), rarity: Rarity.EPIC, title: "Pregunta de Honestidad", description: "Haces una pregunta seria y el otro debe responder sin enojarse." },
  { id: uuid(), rarity: Rarity.EPIC, title: "Palabra Detén-Todo", description: "Acuerden una palabra que pare cualquier discusión al momento." },
  { id: uuid(), rarity: Rarity.EPIC, title: "Cambio de Perspectiva", description: "El receptor debe explicar por qué tú podrías tener razón en algo." },
  { id: uuid(), rarity: Rarity.EPIC, title: "Tregua de 24 Horas", description: "Prohibido hablar de temas estresantes por todo un día." },
  { id: uuid(), rarity: Rarity.EPIC, title: "Refuerzo de Confianza", description: "El receptor debe decirte por qué se siente seguro a tu lado." },
  { id: uuid(), rarity: Rarity.EPIC, title: "Cero Caras", description: "El receptor no puede hacer gestos de molestia mientras hablas hoy." },
  { id: uuid(), rarity: Rarity.EPIC, title: "Día de la Gratitud", description: "Hoy solo se permiten comentarios positivos sobre su relación." },
  { id: uuid(), rarity: Rarity.EPIC, title: "Acuerdo de Solución", description: "Se sientan a escribir cómo arreglarán un problema y lo firman." },
  { id: uuid(), rarity: Rarity.EPIC, title: "Momento de Vulnerabilidad", description: "Hablar de un miedo personal sin temor a ser juzgado." },
  { id: uuid(), rarity: Rarity.EPIC, title: "Apoyo en Estrés", description: "Si tuviste un mal día, el receptor se encarga de todo lo logístico hoy." },
  { id: uuid(), rarity: Rarity.EPIC, title: "Beso de Pausa", description: "Cada vez que la tensión suba, deben darse un beso para calmarse." },
  { id: uuid(), rarity: Rarity.EPIC, title: "Sin Pasado", description: "Prohibido mencionar errores de hace más de un mes durante el día de hoy." },
  { id: uuid(), rarity: Rarity.EPIC, title: "El 'Sí' al Arreglo", description: "Si buscas la paz, el receptor debe aceptar de inmediato." },
  { id: uuid(), rarity: Rarity.EPIC, title: "Tiempo Fuera", description: "Acuerdan no tocar el tema por una hora hasta que bajen los ánimos." },
  { id: uuid(), rarity: Rarity.EPIC, title: "Cero Discusión de Gastos", description: "Prohibido hablar de deudas o dinero durante hoy." },
  { id: uuid(), rarity: Rarity.EPIC, title: "Promesa de Mejora", description: "El receptor se compromete a cambiar un pequeño hábito que te molesta." },
  { id: uuid(), rarity: Rarity.EPIC, title: "Mensaje 'Estoy contigo'", description: "Un texto de apoyo inesperado durante sus labores diarias." },
  { id: uuid(), rarity: Rarity.EPIC, title: "Voz Baja", description: "Si el tono sube, esta carta obliga a ambos a hablar casi susurrando." },
  { id: uuid(), rarity: Rarity.EPIC, title: "Validación", description: "El receptor debe decirte: 'Tus sentimientos son válidos y te entiendo'." },
  { id: uuid(), rarity: Rarity.EPIC, title: "Respeto Familiar", description: "Prohibido hacer críticas sobre la familia del otro durante hoy." },
  { id: uuid(), rarity: Rarity.EPIC, title: "Tiempo de Calidad", description: "Se cancelan compromisos personales para resolver algo de pareja hoy." },
  { id: uuid(), rarity: Rarity.EPIC, title: "Refuerzo Positivo", description: "Por cada cosa que no le guste, el receptor debe decir dos que sí le gusten." },
  { id: uuid(), rarity: Rarity.EPIC, title: "Confesión con Amor", description: "Decir algo que le molesta pero de forma muy constructiva y tierna." },
  { id: uuid(), rarity: Rarity.EPIC, title: "Pausa Dramática", description: "Si están alterados, deben separarse 15 min antes de seguir hablando." },
  { id: uuid(), rarity: Rarity.EPIC, title: "Beso de Perdón", description: "Se sella una disculpa con un beso largo." },
  { id: uuid(), rarity: Rarity.EPIC, title: "Noche sin Ruido", description: "Nada de tele o música alta, solo compañía mutua." },
  { id: uuid(), rarity: Rarity.EPIC, title: "Escucha de Sueños", description: "El receptor escucha tus planes de vida sin cuestionarlos." },
  { id: uuid(), rarity: Rarity.EPIC, title: "Ceder el Mando", description: "El otro toma las decisiones difíciles por ti hoy." },
  { id: uuid(), rarity: Rarity.EPIC, title: "Visión 5 Años", description: "Compartir cómo se ven juntos a largo plazo." },
  { id: uuid(), rarity: Rarity.EPIC, title: "Objeto de Recuerdo", description: "Llevar un objeto del otro todo el día como amuleto." },
  { id: uuid(), rarity: Rarity.EPIC, title: "Cierre de Capítulo", description: "Deciden no volver a hablar de un malentendido pasado." },

  // --- LEGENDARY (YELLOW) ---
  { id: uuid(), rarity: Rarity.LEGENDARY, title: "Se ve más rico lo tuyo", description: "Intercambio de platillos. Disfruta lo mío y yo lo tuyo." },
  { id: uuid(), rarity: Rarity.LEGENDARY, title: "La Carta de 'Toxicidad Aprobada'", description: "Planes cancelados. Hoy no sales, te quedas conmigo. Nada personal." },
  { id: uuid(), rarity: Rarity.LEGENDARY, title: "Te Extraño", description: "Necesito verte. Detén lo que estés haciendo y ven a verme YA." },
  { id: uuid(), rarity: Rarity.LEGENDARY, title: "El Jefe / La Jefa", description: "El receptor debe decir 'Sí, mi amor' a tus peticiones por 3 horas." },
  { id: uuid(), rarity: Rarity.LEGENDARY, title: "Luz Verde de Gasto", description: "Puedes comprarte ese antojo y el otro no puede cuestionarlo." },
  { id: uuid(), rarity: Rarity.LEGENDARY, title: "Cero Amigos hoy", description: "El receptor cancela su salida con otros para estar solo contigo." },
  { id: uuid(), rarity: Rarity.LEGENDARY, title: "Chef Privado", description: "El receptor debe prepararte una comida completa hoy." },
  { id: uuid(), rarity: Rarity.LEGENDARY, title: "Sin Redes Sociales", description: "El receptor no puede usar apps de ocio por 24 horas." },
  { id: uuid(), rarity: Rarity.LEGENDARY, title: "Chofer Privado", description: "Durante el fin de semana, el receptor maneja a donde tú quieras." },
  { id: uuid(), rarity: Rarity.LEGENDARY, title: "Veto de Hobby", description: "El receptor debe guardar su distracción favorita por un día entero." },
  { id: uuid(), rarity: Rarity.LEGENDARY, title: "Outfitter Personal", description: "Tú decides qué ropa y peinado usará el receptor hoy." },
  { id: uuid(), rarity: Rarity.LEGENDARY, title: "Día de Reyes", description: "Desayuno, comida y cena servidos en donde tú estés." },
  { id: uuid(), rarity: Rarity.LEGENDARY, title: "Confesión de Fotos", description: "El receptor te muestra sus últimas fotos o videos del cel." },
  { id: uuid(), rarity: Rarity.LEGENDARY, title: "Inmunidad Total", description: "Eres inmune a cualquier queja o tarea por las próximas 12 horas." },
  { id: uuid(), rarity: Rarity.LEGENDARY, title: "Control de Tele", description: "Tú decides qué se ve en la pantalla todo el fin de semana." },
  { id: uuid(), rarity: Rarity.LEGENDARY, title: "Viaje Planeado", description: "El receptor debe organizar una salida especial para el próximo descanso." },
  { id: uuid(), rarity: Rarity.LEGENDARY, title: "Día de Spa", description: "Masaje completo y mimos hechos por el receptor en casa." },
  { id: uuid(), rarity: Rarity.LEGENDARY, title: "Cero Deportes", description: "El receptor acepta no ver partidos para hacer algo contigo hoy." },
  { id: uuid(), rarity: Rarity.LEGENDARY, title: "Deseo Concedido", description: "Pide un favor grande y el receptor debe cumplirlo hoy." },
  { id: uuid(), rarity: Rarity.LEGENDARY, title: "El Silenciador", description: "El receptor no puede hablar por 20 min; solo gestos y mimos." },
  { id: uuid(), rarity: Rarity.LEGENDARY, title: "Post de Amor", description: "El receptor sube una foto tuya a sus redes con un texto lindo." },
  { id: uuid(), rarity: Rarity.LEGENDARY, title: "Salida Temprana", description: "El receptor sale de su trabajo/estudio puntual para verte." },
  { id: uuid(), rarity: Rarity.LEGENDARY, title: "Beso en Público", description: "El receptor debe darte un beso apasionado en un lugar lleno." },
  { id: uuid(), rarity: Rarity.LEGENDARY, title: "Cambio de Roles", description: "El receptor hace tus tareas habituales por un día entero." },
  { id: uuid(), rarity: Rarity.LEGENDARY, title: "Fantasía de Cena", description: "Tú eliges el tema de la noche y el receptor accede." },
  { id: uuid(), rarity: Rarity.LEGENDARY, title: "Robo de Tiempo", description: "El receptor debe dejar su compromiso para estar contigo 1 hora antes." },
  { id: uuid(), rarity: Rarity.LEGENDARY, title: "Sin Ahorita", description: "A lo que pidas, el receptor debe hacerlo al instante." },
  { id: uuid(), rarity: Rarity.LEGENDARY, title: "Día de Compras", description: "El receptor te acompaña y carga todo lo que compres hoy." },
  { id: uuid(), rarity: Rarity.LEGENDARY, title: "Semana Planeada", description: "El receptor organiza 7 días de actividades sin preguntarte." },
  { id: uuid(), rarity: Rarity.LEGENDARY, title: "Voto Decisivo", description: "En cualquier plan de hoy, tú tienes la última palabra." },
  { id: uuid(), rarity: Rarity.LEGENDARY, title: "Cero Celular en Citas", description: "El teléfono del receptor se queda apagado toda la noche." },
  { id: uuid(), rarity: Rarity.LEGENDARY, title: "Desayuno Especial", description: "El receptor debe salir a traerte tu comida favorita temprano." },
  { id: uuid(), rarity: Rarity.LEGENDARY, title: "Cero Crítica a Amigos", description: "El receptor no puede decir nada malo de tu círculo social hoy." },
  { id: uuid(), rarity: Rarity.LEGENDARY, title: "Regalo Inesperado", description: "El receptor tiene 1 hora para traerte un detalle que te guste." },
  { id: uuid(), rarity: Rarity.LEGENDARY, title: "Maratón de Cine", description: "Vemos todas tus películas favoritas seguidas hoy." },
  { id: uuid(), rarity: Rarity.LEGENDARY, title: "Servicio Total", description: "No te mueves del sofá y el otro te trae todo lo que pidas." },
  { id: uuid(), rarity: Rarity.LEGENDARY, title: "Fin de Semana Libre", description: "Tú eliges todas las actividades de sábado y domingo." },
  { id: uuid(), rarity: Rarity.LEGENDARY, title: "Inversión de Roles", description: "El receptor actúa como tú y tú como él por 1 hora." },
  { id: uuid(), rarity: Rarity.LEGENDARY, title: "Deseo Especial", description: "Pide cualquier cosa (dentro de lo posible) y se te concede." },
  { id: uuid(), rarity: Rarity.LEGENDARY, title: "La Última Palabra", description: "Tú cierras cualquier decisión que se tome hoy." },

  // --- SPECIAL (GREEN) ---
  { id: uuid(), rarity: Rarity.SPECIAL, title: "La Carta de 'NOP'", description: "Cancela completamente cualquier carta que te acaban de lanzar." },
  { id: uuid(), rarity: Rarity.SPECIAL, title: "Espejo", description: "Devuelve el efecto de la carta al lanzador. Ahora tú obtienes el beneficio." },
  { id: uuid(), rarity: Rarity.SPECIAL, title: "Reversa", description: "Si te piden algo físico, ahora el otro debe hacerlo por ti." },
  { id: uuid(), rarity: Rarity.SPECIAL, title: "Robo de Botín", description: "Le quitas una carta del mazo a tu pareja y es tuya." },
  { id: uuid(), rarity: Rarity.SPECIAL, title: "Trabajo Hecho, Botín Ganado", description: "Cumples la carta, pero te la quedas para usarla de nuevo." },
  { id: uuid(), rarity: Rarity.SPECIAL, title: "Doble o Nada", description: "El efecto de la carta se duplica en tiempo o intensidad." },
  { id: uuid(), rarity: Rarity.SPECIAL, title: "Silenciador de NOP", description: "Invalida el 'NOP' de tu pareja; tu carta se cumple sí o sí." },
  { id: uuid(), rarity: Rarity.SPECIAL, title: "Escudo Protector", description: "No te pueden lanzar cartas por las próximas 3 horas." },
  { id: uuid(), rarity: Rarity.SPECIAL, title: "Intercambio de Mazos", description: "Cambian todas sus cartas restantes ahora mismo." },
  { id: uuid(), rarity: Rarity.SPECIAL, title: "Segunda Oportunidad", description: "Obliga al otro a repetir una carta porque 'no lo hizo bien'." },
  { id: uuid(), rarity: Rarity.SPECIAL, title: "Tregua Temporal", description: "Se pausan las cartas por el resto del día de hoy." },
  { id: uuid(), rarity: Rarity.SPECIAL, title: "Peaje de Besos", description: "El otro debe darte 5 besos para poder jugar su carta." },
  { id: uuid(), rarity: Rarity.SPECIAL, title: "Multa por Queja", description: "Si el otro protesta, te entrega una carta al azar de su mazo." },
  { id: uuid(), rarity: Rarity.SPECIAL, title: "Carta del Destino", description: "Saca una carta del mazo del otro y úsala contra él." },
  { id: uuid(), rarity: Rarity.SPECIAL, title: "Inmune a la Toxicidad", description: "Te protege específicamente de las tarjetas amarillas." },
  { id: uuid(), rarity: Rarity.SPECIAL, title: "Prórroga", description: "Aceptas la carta, pero se cumple hasta el día siguiente." },
  { id: uuid(), rarity: Rarity.SPECIAL, title: "Comodín de Regla", description: "Inventa una regla nueva para el juego por 24 horas." },
  { id: uuid(), rarity: Rarity.SPECIAL, title: "Espejo Rebotador", description: "Anula el espejo de tu pareja; tu carta original vuelve a ella." },
  { id: uuid(), rarity: Rarity.SPECIAL, title: "Activación de Beso", description: "Ninguna carta tuya vale si no me das un beso de 10 segundos." },
  { id: uuid(), rarity: Rarity.SPECIAL, title: "Fin del Juego Temporada 1", description: "Cancela todos los efectos activos en este momento." },
  { id: uuid(), rarity: Rarity.SPECIAL, title: "Ladrón de Suerte", description: "Si el otro saca una Legendaria, ahora es de tu propiedad." },
  { id: uuid(), rarity: Rarity.SPECIAL, title: "Sustitución", description: "Cambia la tarea de la carta por algo que te guste más hoy." },
  { id: uuid(), rarity: Rarity.SPECIAL, title: "Espionaje", description: "Mira 5 cartas del mazo de tu pareja en secreto." },
  { id: uuid(), rarity: Rarity.SPECIAL, title: "Bloqueo de Color", description: "Tu pareja no puede jugar cartas de un color específico por 3 horas." },
  { id: uuid(), rarity: Rarity.SPECIAL, title: "Transferencia", description: "La tarea se intercambia por un favor que te deban a futuro." },
  { id: uuid(), rarity: Rarity.SPECIAL, title: "Pausa de 5 Minutos", description: "Tienes tiempo para decidir si usas una defensa o no." },
  { id: uuid(), rarity: Rarity.SPECIAL, title: "Hechizo de Risa", description: "Si el otro se ríe al lanzarte la carta, esta se anula." },
  { id: uuid(), rarity: Rarity.SPECIAL, title: "Bono de Cariño", description: "Si haces la tarea rápido, recuperas una carta usada." },
  { id: uuid(), rarity: Rarity.SPECIAL, title: "Cero Verdes", description: "Nadie puede usar cartas especiales por las próximas 4 horas." },
  { id: uuid(), rarity: Rarity.SPECIAL, title: "Mazo Infinito", description: "Recupera una carta que ya hayas jugado anteriormente." },
  { id: uuid(), rarity: Rarity.SPECIAL, title: "Sacrificio", description: "Descarta 3 comunes para anular una Épica." },
  { id: uuid(), rarity: Rarity.SPECIAL, title: "Teletransporte", description: "La carta que me jugaste se aplica a ti cuando nos veamos." },
  { id: uuid(), rarity: Rarity.SPECIAL, title: "Reflejo de Tarea", description: "Si me pides algo, tú también lo haces después por mí." },
  { id: uuid(), rarity: Rarity.SPECIAL, title: "Anulador de Reglas", description: "Por 15 min ignoramos las reglas básicas del juego." },
  { id: uuid(), rarity: Rarity.SPECIAL, title: "Doble Cara", description: "Esta carta copia el efecto de la última que jugó tu pareja." },
  { id: uuid(), rarity: Rarity.SPECIAL, title: "Inmunidad por Abrazo", description: "Mientras nos estemos abrazando, no puedes lanzarme cartas." },
  { id: uuid(), rarity: Rarity.SPECIAL, title: "Sorteo", description: "Barajamos 3 cartas y la que salga se cumple hoy." },
  { id: uuid(), rarity: Rarity.SPECIAL, title: "Última Palabra", description: "Yo decido exactamente cómo se cumple la carta." },
  { id: uuid(), rarity: Rarity.SPECIAL, title: "Poder Compartido", description: "El beneficio de tu carta aplica para los dos hoy." },
  { id: uuid(), rarity: Rarity.SPECIAL, title: "Beso de Cierre", description: "El juego se pausa con un beso largo de despedida." },
];

export const MOCK_USER_ID = "user_123";
export const MOCK_PARTNER_ID = "user_456";